services:
  rabbitmq:
    image: "bitnami/rabbitmq:latest"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq

  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DATABASE=0
    ports:
      - "6379:6379"
  celery-flower:
    image: gregsi/latest-celery-flower-docker:latest
    environment:
      - AMQP_USERNAME=guest
      - AMQP_PASSWORD=guest
      - AMQP_ADMIN_USERNAME=guest
      - AMQP_ADMIN_PASSWORD=guest
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_ADMIN_HOST=rabbitmq
      - AMQP_ADMIN_PORT=15672
      - FLOWER_BASIC_AUTH=guest:guest
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
